

IF (:NEW.ID_OPERACAO				<> :OLD.ID_OPERACAO				) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_OPERACAO				, :OLD.ID_OPERACAO				,'ID_OPERACAO'			,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;
IF (:NEW.ID_FILIAL					<> :OLD.ID_FILIAL				) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_FILIAL					, :OLD.ID_FILIAL				,'ID_FILIAL'			,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;	
IF (:NEW.ID_EMPRESA					<> :OLD.ID_EMPRESA				) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_EMPRESA				, :OLD.ID_EMPRESA				,'ID_EMPRESA'			,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;	
IF (:NEW.ID_NAVIO					<> :OLD.ID_NAVIO				) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_NAVIO					, :OLD.ID_NAVIO					,'ID_NAVIO'				,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;	
IF (:NEW.ID_CONTRATO				<> :OLD.ID_CONTRATO				) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_CONTRATO				, :OLD.ID_CONTRATO				,'ID_CONTRATO'			,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;
IF (:NEW.NR_VIAGEM					<> :OLD.NR_VIAGEM				) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.NR_VIAGEM					, :OLD.NR_VIAGEM				,'NR_VIAGEM'			,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;	
IF (:NEW.ID_AGENTE					<> :OLD.ID_AGENTE				) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_AGENTE					, :OLD.ID_AGENTE				,'ID_AGENTE'			,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;	
IF (:NEW.ID_ARMADOR					<> :OLD.ID_ARMADOR				) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_ARMADOR				, :OLD.ID_ARMADOR				,'ID_ARMADOR'			,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;	
IF (:NEW.IND_OP_COMPARTILHADA		<> :OLD.IND_OP_COMPARTILHADA	) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.IND_OP_COMPARTILHADA		, :OLD.IND_OP_COMPARTILHADA		,'IND_OP_COMPARTILHAD'	,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;	
IF (:NEW.IND_TP_TARIFA				<> :OLD.IND_TP_TARIFA			) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.IND_TP_TARIFA				, :OLD.IND_TP_TARIFA			,'IND_TP_TARIFA'		,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;	
IF (:NEW.SITUACAO					<> :OLD.SITUACAO				) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.SITUACAO					, :OLD.SITUACAO					,'SITUACAO'				,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;	
IF (:NEW.ID_OPERACAO_OLD			<> :OLD.ID_OPERACAO_OLD			) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_OPERACAO_OLD			, :OLD.ID_OPERACAO_OLD			,'ID_OPERACAO_OLD'		,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;
IF (:NEW.ID_DOM_TP_CARGA			<> :OLD.ID_DOM_TP_CARGA			) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_DOM_TP_CARGA			, :OLD.ID_DOM_TP_CARGA			,'ID_DOM_TP_CARGA'		,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;
IF (:NEW.NR_FATURA					<> :OLD.NR_FATURA				) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.NR_FATURA					, :OLD.NR_FATURA				,'NR_FATURA'			,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;	
IF (:NEW.OBS_APR_REP				<> :OLD.OBS_APR_REP				) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.OBS_APR_REP				, :OLD.OBS_APR_REP				,'OBS_APR_REP'			,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;
IF (:NEW.ID_DOM_MOTV_CANC			<> :OLD.ID_DOM_MOTV_CANC		) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_DOM_MOTV_CANC			, :OLD.ID_DOM_MOTV_CANC			,'ID_DOM_MOTV_CANC'		,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;	
IF (:NEW.ID_USUARIO_CAD				<> :OLD.ID_USUARIO_CAD			) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_USUARIO_CAD			, :OLD.ID_USUARIO_CAD			,'ID_USUARIO_CAD'		,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;	
IF (:NEW.DT_IMP_NOTA_FISCAL			<> :OLD.DT_IMP_NOTA_FISCAL		) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.DT_IMP_NOTA_FISCAL		, :OLD.DT_IMP_NOTA_FISCAL		,'DT_IMP_NOTA_FISCA'	,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;	
IF (:NEW.FAT_NF						<> :OLD.FAT_NF					) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.FAT_NF					, :OLD.FAT_NF					,'FAT_NF'				,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;	
IF (:NEW.FAT_DTSAIDA				<> :OLD.FAT_DTSAIDA				) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.FAT_DTSAIDA				, :OLD.FAT_DTSAIDA				,'FAT_DTSAIDA'			,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;
IF (:NEW.DT_IMPRESSAO_INVOICE		<> :OLD.DT_IMPRESSAO_INVOICE	) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.DT_IMPRESSAO_INVOICE		, :OLD.DT_IMPRESSAO_INVOICE		,'DT_IMPRESSAO_INVOIC'	,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;	
IF (:NEW.FAT_TAXA					<> :OLD.FAT_TAXA				) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.FAT_TAXA					, :OLD.FAT_TAXA					,'FAT_TAXA'				,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;	
IF (:NEW.IND_PREVISTA				<> :OLD.IND_PREVISTA			) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.IND_PREVISTA				, :OLD.IND_PREVISTA				,'IND_PREVISTA'			,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;	
IF (:NEW.ID_AJUSTE_TARIFA			<> :OLD.ID_AJUSTE_TARIFA		) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_AJUSTE_TARIFA			, :OLD.ID_AJUSTE_TARIFA			,'ID_AJUSTE_TARIFA'		,'TB_OPERACAO',user_a,user_b,:NEW.ID_OPERACAO); end if;	



IF (:NEW.ID_MANOBRA_OPERACAO		<> :OLD.ID_MANOBRA_OPERACAO		) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_MANOBRA_OPERACAO		, :OLD.ID_MANOBRA_OPERACAO	,'ID_MANOBRA_OPERACAO'		,'TB_MANOBRA_OPERACAO',user_a,user_b,:new.ID_MANOBRA_OPERACAO);end if;						
IF (:NEW.ID_OPERACAO				<> :OLD.ID_OPERACAO				) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_OPERACAO				, :OLD.ID_OPERACAO			,'ID_OPERACAO'				,'TB_MANOBRA_OPERACAO',user_a,user_b,:new.ID_MANOBRA_OPERACAO);end if;		
IF (:NEW.ID_LOCAL_MANOBRA			<> :OLD.ID_LOCAL_MANOBRA		) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_LOCAL_MANOBRA			, :OLD.ID_LOCAL_MANOBRA		,'ID_LOCAL_MANOBRA'			,'TB_MANOBRA_OPERACAO',user_a,user_b,:new.ID_MANOBRA_OPERACAO);end if;					
IF (:NEW.ID_TIPO_MANOBRA			<> :OLD.ID_TIPO_MANOBRA			) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_TIPO_MANOBRA			, :OLD.ID_TIPO_MANOBRA		,'ID_TIPO_MANOBRA'			,'TB_MANOBRA_OPERACAO',user_a,user_b,:new.ID_MANOBRA_OPERACAO);end if;				
IF (:NEW.LOCAL_INICIO				<> :OLD.LOCAL_INICIO			) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.LOCAL_INICIO				, :OLD.LOCAL_INICIO			,'LOCAL_INICIO'				,'TB_MANOBRA_OPERACAO',user_a,user_b,:new.ID_MANOBRA_OPERACAO);end if;			
IF (:NEW.LOCAL_FIM					<> :OLD.LOCAL_FIM				) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.LOCAL_FIM					, :OLD.LOCAL_FIM			,'LOCAL_FIM'				,'TB_MANOBRA_OPERACAO',user_a,user_b,:new.ID_MANOBRA_OPERACAO);end if;	
IF (:NEW.ID_OPERACAO_OLD			<> :OLD.ID_OPERACAO_OLD			) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_OPERACAO_OLD			, :OLD.ID_OPERACAO_OLD		,'ID_OPERACAO_OLD'			,'TB_MANOBRA_OPERACAO',user_a,user_b,:new.ID_MANOBRA_OPERACAO);end if;				
IF (:NEW.VL_HORA_MANOBRA			<> :OLD.VL_HORA_MANOBRA			) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.VL_HORA_MANOBRA			, :OLD.VL_HORA_MANOBRA		,'VL_HORA_MANOBRA'			,'TB_MANOBRA_OPERACAO',user_a,user_b,:new.ID_MANOBRA_OPERACAO);end if;				
IF (:NEW.VL_MANOBRA					<> :OLD.VL_MANOBRA				) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.VL_MANOBRA				, :OLD.VL_MANOBRA			,'VL_MANOBRA'				,'TB_MANOBRA_OPERACAO',user_a,user_b,:new.ID_MANOBRA_OPERACAO);end if;	
IF (:NEW.VL_DESCONTO_TARIFA			<> :OLD.VL_DESCONTO_TARIFA		) then INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.VL_DESCONTO_TARIFA		, :OLD.VL_DESCONTO_TARIFA	,'VL_DESCONTO_TARIFA'		,'TB_MANOBRA_OPERACAO',user_a,user_b,:new.ID_MANOBRA_OPERACAO);end if;							


IF (:NEW.ID_MANOBRA_OPERACAO	<> :OLD.ID_MANOBRA_OPERACAO	) THEN  INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_MANOBRA_OPERACAO	, :OLD.ID_MANOBRA_OPERACAO	,'ID_MANOBRA_OPERACAO' 	,'TB_REBOCADOR_MANOBRA',user_a,user_b); END IF;
IF (:NEW.ID_REBOCADOR			<> :OLD.ID_REBOCADOR		) THEN  INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_REBOCADOR			, :OLD.ID_REBOCADOR			,'ID_REBOCADOR' 		,'TB_REBOCADOR_MANOBRA',user_a,user_b); END IF;
IF (:NEW.MDB					<> :OLD.MDB					) THEN  INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.MDB					, :OLD.MDB					,'MDB' 					,'TB_REBOCADOR_MANOBRA',user_a,user_b); END IF;
IF (:NEW.DATA_INICIO			<> :OLD.DATA_INICIO			) THEN  INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.DATA_INICIO			, :OLD.DATA_INICIO			,'DATA_INICIO'  		,'TB_REBOCADOR_MANOBRA',user_a,user_b); END IF;
IF (:NEW.DATA_FIM				<> :OLD.DATA_FIM			) THEN  INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.DATA_FIM				, :OLD.DATA_FIM				,'DATA_FIM' 			,'TB_REBOCADOR_MANOBRA',user_a,user_b); END IF;
IF (:NEW.HORA_INICIO			<> :OLD.HORA_INICIO			) THEN  INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.HORA_INICIO			, :OLD.HORA_INICIO			,'HORA_INICIO' 			,'TB_REBOCADOR_MANOBRA',user_a,user_b); END IF;
IF (:NEW.HORA_FIM				<> :OLD.HORA_FIM			) THEN  INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.HORA_FIM				, :OLD.HORA_FIM				,'HORA_FIM' 			,'TB_REBOCADOR_MANOBRA',user_a,user_b); END IF;
IF (:NEW.ID_REBOCADOR_OLD		<> :OLD.ID_REBOCADOR_OLD	) THEN  INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_REBOCADOR_OLD		, :OLD.ID_REBOCADOR_OLD		,'ID_REBOCADOR_OLD' 	,'TB_REBOCADOR_MANOBRA',user_a,user_b); END IF;
IF (:NEW.ID_DOM_MOTIVO_UTILZ	<> :OLD.ID_DOM_MOTIVO_UTILZ	) THEN  INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.ID_DOM_MOTIVO_UTILZ	, :OLD.ID_DOM_MOTIVO_UTILZ	,'ID_DOM_MOTIVO_UTILZ' 	,'TB_REBOCADOR_MANOBRA',user_a,user_b); END IF;
IF (:NEW.IND_AFRETAMENTO		<> :OLD.IND_AFRETAMENTO		) THEN  INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.IND_AFRETAMENTO		, :OLD.IND_AFRETAMENTO		,'IND_AFRETAMENTO' 		,'TB_REBOCADOR_MANOBRA',user_a,user_b); END IF;
IF (:NEW.VL_DESCONTO_MANOBRA	<> :OLD.VL_DESCONTO_MANOBRA	) THEN  INSERT INTO tb_logger(new_val,old_val,column_name,table_name,user_a,user_b,PK) values(:NEW.VL_DESCONTO_MANOBRA	, :OLD.VL_DESCONTO_MANOBRA	,'VL_DESCONTO_MANOBRA' 	,'TB_REBOCADOR_MANOBRA',user_a,user_b); END IF;


alter table mytable add date_created date default null;

alter table mytable modify date_created default sysdate;